stages:
  - deploy

cache:
  paths:
  - vendor/
  - node_modules/

deploy_dev:
  stage: deploy
  before_script:
      - eval $(ssh-agent -s)
      - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
      - mkdir -p ~/.ssh
      - chmod 700 ~/.ssh
  script:
    - ssh -o "StrictHostKeyChecking no" dani@188.166.35.94 "cd /var/www/html/pre && cd project-lightning && git pull && ./pre-deploy.sh"
  only:
  - dev

    

